name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |

          mkdir -p build && cd build
          cmake -DRUN_COVERAGE=1 .. && make -j2

          echo "Running command: cmake -DRUN_COVERAGE=1 .. && make -j2"

          if [ $? -ne 0 ]; then
            echo "Compilation failed."
            exit 1
          fi
