name: Workflow for Quality Assurance

on:
  workflow_dispatch:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  RunQAChecks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format valgrind bc
          version: 1.2

      - name: Build project
        uses: ./.github/actions/configure-and-build

      - name: Run style check
        uses: ./.github/actions/style-check

      - name: Run documentation check
        uses: ./.github/actions/doc-check

      - name: Run test and coverage check
        uses: ./.github/actions/test-and-coverage
